version: 2
root-markers:
  - .git/
lint-debounce: 1s
commands:
  - command: notepad
    arguments:
      - ${INPUT}
    title: メモ帳

tools:
  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  python-isort: &python-isort
    format-command: 'isort --stdout -'
    format-stdin: true

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-darglint: &python-darglint
    lint-command: 'darglint --docstring-style sphinx -v 2 -z long -'
    lint-stdin: true

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i'
    format-stdin: true

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

languages:
  python:
    - <<: *python-flake8
    - <<: *python-black
    - <<: *python-isort
    - <<: *python-darglint

  lua:
    - <<: *lua-lua-format

  yaml:
    - <<: *yaml-yamllint
